-- =====================================================================
-- LUCCA CAFFE POS — Supabase PostgreSQL Schema v2 (Phase 1)
-- =====================================================================
-- الهدف: سكيمة كاملة تطابق مخطط SQLite (db.ts + migrations + أدوات العميل)
-- مع سياسات RLS مصمّمة حسب الدور (cashier / manager / admin) منذ البداية.
--
-- مَن يستخدم ماذا:
--   • الخادم (backend)  → service_role key  → يتجاوز RLS تماماً (المصدر الرئيسي).
--   • العميل (أونلاين)  → anon key          → يخضع لـ RLS (قراءة عامة للقائمة فقط).
--   • مستخدمو Supabase Auth → أي دور مخوَّل وفق app_user_roles.
--
-- ملاحظات تحويل الأنواع من SQLite:
--   REAL        → DOUBLE PRECISION  (SQLite REAL عائم 64bit — لا نفقد دقة الأسعار)
--   TEXT dates  → TEXT  (تُخزَّن كما هي 'YYYY-MM-DD' .. لا أخطاء توقيت/منطقة)
--   datetime('now') → NOW()  (TIMESTAMPTZ)
--   INTEGER PK AUTOINCREMENT → BIGSERIAL  |  أسماء الأعمدة camelCase تُحاط بعلامتي اقتباس
--
-- التشغيل: Supabase Dashboard > SQL Editor > لصق وتشغيل.
-- بعدها: أنشئ مستخدمي Auth تجريبيين عبر deploy/supabase-rls-seed.sql
--        ثم تحقق من RLS عبر tools/test-supabase-rls.cjs
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================================
-- أدوات RLS حسب الدور
-- =====================================================================
-- خريطة مستخدم Supabase Auth → دوره في النظام. لا يوجد صف = لا وصول.
CREATE TABLE IF NOT EXISTS app_user_roles (
  user_id   UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role      TEXT NOT NULL CHECK (role IN ('admin','manager','cashier','kitchen','device')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP FUNCTION IF EXISTS public.current_app_role CASCADE;
CREATE OR REPLACE FUNCTION public.current_app_role()
RETURNS TEXT
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT role FROM public.app_user_roles WHERE user_id = auth.uid() LIMIT 1;
$$;

DROP FUNCTION IF EXISTS public.role_in CASCADE;
CREATE OR REPLACE FUNCTION public.role_in(allowed TEXT[])
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT current_app_role() = ANY(allowed);
$$;

DROP FUNCTION IF EXISTS public.is_staff CASCADE;
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT role_in(ARRAY['cashier','manager','admin']);
$$;

DROP FUNCTION IF EXISTS public.is_manager CASCADE;
CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT role_in(ARRAY['manager','admin']);
$$;

DROP FUNCTION IF EXISTS public.is_admin CASCADE;
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT role_in(ARRAY['admin']);
$$;

-- =====================================================================
-- الجداول الأساسية — camelCase مطابق تماماً لمخطط db.ts
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
  "id" BIGSERIAL PRIMARY KEY,
  "username" TEXT UNIQUE NOT NULL,
  "email" TEXT,
  "password" TEXT NOT NULL,
  "name" TEXT DEFAULT '',
  "role" TEXT DEFAULT 'cashier',
  "active" INTEGER DEFAULT 1,
  "employeeId" BIGINT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "mustChangePassword" INTEGER DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users("email") WHERE "email" IS NOT NULL AND "email" <> '';

CREATE TABLE IF NOT EXISTS tables_store (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" INTEGER,
  "status" TEXT DEFAULT 'available' CHECK ("status" IN ('available','occupied','reserved','cleaning','closed')),
  "capacity" INTEGER DEFAULT 4,
  "currentOrder" BIGINT,
  "zone" TEXT DEFAULT 'صالة',
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);
-- عرض توافقي (الاسم القديم 'tables' كان جدولاً في SQLite — هنا VIEW للخلفية)
-- security_invoker: يضمن تطبيق RLS للمستدعي أسفل العرض (لا يفوت السياسات بحقوق المالك)
CREATE OR REPLACE VIEW tables WITH (security_invoker = true) AS SELECT * FROM tables_store;

CREATE TABLE IF NOT EXISTS categories (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "name_ar" TEXT DEFAULT '',
  "name_en" TEXT DEFAULT '',
  "icon" TEXT DEFAULT '',
  "color" TEXT DEFAULT '',
  "image" TEXT DEFAULT '',
  "sortOrder" INTEGER DEFAULT 0,
  "active" INTEGER DEFAULT 1,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT
);

CREATE TABLE IF NOT EXISTS products (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "name_ar" TEXT DEFAULT '',
  "name_en" TEXT DEFAULT '',
  "sku" TEXT DEFAULT '',
  "categoryId" BIGINT,
  "price" DOUBLE PRECISION DEFAULT 0,
  "cost" DOUBLE PRECISION DEFAULT 0,
  "taxRate" DOUBLE PRECISION DEFAULT 0,
  "image" TEXT DEFAULT '',
  "description" TEXT DEFAULT '',
  "components" TEXT DEFAULT '[]',
  "badge" TEXT DEFAULT '',
  "available" INTEGER DEFAULT 1,
  "productType" TEXT DEFAULT 'standard' CHECK ("productType" IN ('standard','modifier','combo')),
  "sortOrder" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  FOREIGN KEY ("categoryId") REFERENCES categories("id")
);

CREATE TABLE IF NOT EXISTS product_modifiers (
  "id" BIGSERIAL PRIMARY KEY,
  "productId" BIGINT NOT NULL,
  "name" TEXT NOT NULL,
  "price" DOUBLE PRECISION DEFAULT 0,
  "sortOrder" INTEGER DEFAULT 0,
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY ("productId") REFERENCES products("id")
);

CREATE TABLE IF NOT EXISTS product_variations (
  "id" BIGSERIAL PRIMARY KEY,
  "productId" BIGINT NOT NULL,
  "name" TEXT NOT NULL,
  "price" DOUBLE PRECISION DEFAULT 0,
  "sku" TEXT DEFAULT '',
  "sortOrder" INTEGER DEFAULT 0,
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY ("productId") REFERENCES products("id")
);

CREATE TABLE IF NOT EXISTS payment_methods (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "name_ar" TEXT DEFAULT '',
  "name_en" TEXT DEFAULT '',
  "type" TEXT DEFAULT 'cash' CHECK ("type" IN ('cash','card','wallet','bank','other')),
  "icon" TEXT DEFAULT '',
  "active" INTEGER DEFAULT 1,
  "sortOrder" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT
);

CREATE TABLE IF NOT EXISTS taxes (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "rate" DOUBLE PRECISION DEFAULT 0,
  "active" INTEGER DEFAULT 1,
  "appliesTo" TEXT DEFAULT 'all' CHECK ("appliesTo" IN ('all','products','orders')),
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT
);

CREATE TABLE IF NOT EXISTS orders (
  "id" BIGSERIAL PRIMARY KEY,
  "orderNumber" TEXT DEFAULT '',
  "tableId" TEXT,
  "orderType" TEXT DEFAULT 'dine_in' CHECK ("orderType" IN ('dine_in','takeaway','delivery','pickup')),
  "items" TEXT DEFAULT '[]',
  "customerName" TEXT DEFAULT '',
  "customerPhone" TEXT DEFAULT '',
  "paymentMethod" TEXT DEFAULT 'cash',
  "paymentMethodId" BIGINT,
  "customerNotes" TEXT DEFAULT '',
  "invoiceDelivery" TEXT DEFAULT 'cashier',
  "marketingOptIn" INTEGER DEFAULT 0,
  "status" TEXT DEFAULT 'pending' CHECK ("status" IN ('pending','in_preparation','ready','served','completed','cancelled','closed')),
  "paymentStatus" TEXT DEFAULT 'unpaid' CHECK ("paymentStatus" IN ('unpaid','partial','paid','refunded')),
  "subtotal" DOUBLE PRECISION DEFAULT 0,
  "discount" DOUBLE PRECISION DEFAULT 0,
  "discountAmount" DOUBLE PRECISION DEFAULT 0,
  "discountType" TEXT DEFAULT 'percent' CHECK ("discountType" IN ('percent','fixed')),
  "discountBy" TEXT DEFAULT '',
  "tax" DOUBLE PRECISION DEFAULT 0,
  "total" DOUBLE PRECISION DEFAULT 0,
  "totalPaid" DOUBLE PRECISION DEFAULT 0,
  "changeAmount" DOUBLE PRECISION DEFAULT 0,
  "date" TIMESTAMPTZ DEFAULT NOW(),
  "createdBy" TEXT DEFAULT 'unknown',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "voidReason" TEXT DEFAULT '',
  "voidNote" TEXT DEFAULT '',
  "voidedAt" TIMESTAMPTZ,
  "voidedBy" TEXT DEFAULT '',
  "refundAmount" DOUBLE PRECISION DEFAULT 0,
  "syncId" TEXT
);

CREATE TABLE IF NOT EXISTS order_items (
  "id" BIGSERIAL PRIMARY KEY,
  "orderId" BIGINT NOT NULL,
  "productId" BIGINT,
  "name" TEXT NOT NULL,
  "quantity" INTEGER DEFAULT 1,
  "unitPrice" DOUBLE PRECISION DEFAULT 0,
  "total" DOUBLE PRECISION DEFAULT 0,
  "cost" DOUBLE PRECISION DEFAULT 0,
  "discount" DOUBLE PRECISION DEFAULT 0,
  "discountType" TEXT DEFAULT 'percent',
  "tax" DOUBLE PRECISION DEFAULT 0,
  "modifiers" TEXT DEFAULT '[]',
  "notes" TEXT DEFAULT '',
  "status" TEXT DEFAULT 'pending' CHECK ("status" IN ('pending','in_preparation','ready','served','cancelled')),
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "orderSyncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY ("orderId") REFERENCES orders("id"),
  FOREIGN KEY ("productId") REFERENCES products("id")
);

CREATE TABLE IF NOT EXISTS order_status_history (
  "id" BIGSERIAL PRIMARY KEY,
  "orderId" BIGINT NOT NULL,
  "status" TEXT NOT NULL,
  "changedBy" TEXT DEFAULT '',
  "notes" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY ("orderId") REFERENCES orders("id")
);

CREATE TABLE IF NOT EXISTS payments (
  "id" BIGSERIAL PRIMARY KEY,
  "orderId" BIGINT NOT NULL,
  "invoiceId" BIGINT,
  "amount" DOUBLE PRECISION NOT NULL,
  "method" TEXT DEFAULT 'cash',
  "paymentMethodId" BIGINT,
  "reference" TEXT DEFAULT '',
  "status" TEXT DEFAULT 'completed' CHECK ("status" IN ('pending','completed','refunded','void')),
  "createdBy" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "orderSyncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY ("orderId") REFERENCES orders("id")
);

CREATE TABLE IF NOT EXISTS refunds (
  "id" BIGSERIAL PRIMARY KEY,
  "orderId" BIGINT NOT NULL,
  "paymentId" BIGINT,
  "amount" DOUBLE PRECISION NOT NULL,
  "reason" TEXT DEFAULT '',
  "type" TEXT DEFAULT 'full' CHECK ("type" IN ('full','partial','item')),
  "createdBy" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "voidedBy" TEXT DEFAULT '',
  "note" TEXT DEFAULT '',
  "refundMethod" TEXT DEFAULT 'cash',
  "syncId" TEXT,
  "orderSyncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY ("orderId") REFERENCES orders("id")
);

CREATE TABLE IF NOT EXISTS audit_logs (
  "id" BIGSERIAL PRIMARY KEY,
  "userId" BIGINT,
  "userName" TEXT DEFAULT '',
  "action" TEXT NOT NULL,
  "objectType" TEXT DEFAULT '',
  "objectId" BIGINT,
  "oldValue" TEXT DEFAULT '',
  "newValue" TEXT DEFAULT '',
  "ipAddress" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS discounts (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "type" TEXT DEFAULT 'percent' CHECK ("type" IN ('percent','fixed')),
  "value" DOUBLE PRECISION DEFAULT 0,
  "minOrderAmount" DOUBLE PRECISION DEFAULT 0,
  "maxUses" INTEGER DEFAULT 0,
  "usedCount" INTEGER DEFAULT 0,
  "active" INTEGER DEFAULT 1,
  "startsAt" TIMESTAMPTZ,
  "endsAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customers (
  "id" BIGSERIAL PRIMARY KEY,
  "phone" TEXT,
  "name" TEXT DEFAULT '',
  "visits" INTEGER DEFAULT 1,
  "lastVisit" TIMESTAMPTZ,
  "totalSpent" DOUBLE PRECISION DEFAULT 0,
  "marketingOptIn" INTEGER DEFAULT 0,
  "preferredChannel" TEXT DEFAULT 'cashier',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  "key" TEXT PRIMARY KEY,
  "value" TEXT
);

CREATE TABLE IF NOT EXISTS inventory (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT,
  "quantity" DOUBLE PRECISION DEFAULT 0,
  "unit" TEXT DEFAULT 'قطعة',
  "minStock" DOUBLE PRECISION DEFAULT 0,
  "costPrice" DOUBLE PRECISION DEFAULT 0,
  "lastUpdated" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS purchases (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT DEFAULT '',
  "item" TEXT DEFAULT '',
  "quantity" DOUBLE PRECISION DEFAULT 1,
  "costPrice" DOUBLE PRECISION DEFAULT 0,
  "total" DOUBLE PRECISION DEFAULT 0,
  "supplier" TEXT DEFAULT '',
  "notes" TEXT DEFAULT '',
  "date" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "createdBy" TEXT DEFAULT 'admin',
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS employees (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT,
  "phone" TEXT DEFAULT '',
  "role" TEXT DEFAULT 'موظف',
  "salary" DOUBLE PRECISION DEFAULT 0,
  "active" INTEGER DEFAULT 1,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "hireDate" TEXT DEFAULT '',
  "email" TEXT,
  "userId" BIGINT,
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attendance (
  "id" BIGSERIAL PRIMARY KEY,
  "employeeId" BIGINT,
  "date" TEXT,
  "checkIn" TIMESTAMPTZ,
  "checkOut" TIMESTAMPTZ,
  "lateMinutes" INTEGER DEFAULT 0,
  "bonus" DOUBLE PRECISION DEFAULT 0,
  "deduction" DOUBLE PRECISION DEFAULT 0,
  "hoursWorked" DOUBLE PRECISION,
  "notes" TEXT DEFAULT '',
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY ("employeeId") REFERENCES employees("id")
);

CREATE TABLE IF NOT EXISTS expenses (
  "id" BIGSERIAL PRIMARY KEY,
  "description" TEXT DEFAULT '',
  "category" TEXT DEFAULT 'أخرى',
  "amount" DOUBLE PRECISION DEFAULT 0,
  "notes" TEXT DEFAULT '',
  "date" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "createdBy" TEXT DEFAULT 'admin',
  "paymentMethod" TEXT DEFAULT 'cash',
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shifts (
  "id" BIGSERIAL PRIMARY KEY,
  "employeeId" BIGINT DEFAULT 0,
  "date" TEXT,
  "startTime" TIMESTAMPTZ,
  "endTime" TIMESTAMPTZ,
  "hoursWorked" DOUBLE PRECISION DEFAULT 0,
  "status" TEXT DEFAULT 'active',
  "notes" TEXT DEFAULT '',
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS daily_shifts (
  "date" TEXT PRIMARY KEY,
  "openingBalance" DOUBLE PRECISION DEFAULT 0,
  "status" TEXT DEFAULT 'open',
  "openedAt" TIMESTAMPTZ DEFAULT NOW(),
  "closedAt" TIMESTAMPTZ,
  "actualCash" DOUBLE PRECISION,
  "expectedCash" DOUBLE PRECISION,
  "difference" DOUBLE PRECISION,
  "cashSales" DOUBLE PRECISION,
  "cardSales" DOUBLE PRECISION,
  "totalSales" DOUBLE PRECISION,
  "totalExpenses" DOUBLE PRECISION,
  "orderCount" INTEGER DEFAULT 0,
  "notes" TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cash_registers (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "status" TEXT DEFAULT 'open',
  "startingCash" DOUBLE PRECISION DEFAULT 0,
  "currentCash" DOUBLE PRECISION DEFAULT 0,
  "openingCash" DOUBLE PRECISION DEFAULT 0,
  "employeeId" BIGINT,
  "openedBy" TEXT DEFAULT '',
  "openedByUser" BIGINT,
  "closedBy" TEXT DEFAULT '',
  "closedByUser" BIGINT,
  "openedAt" TIMESTAMPTZ,
  "closedAt" TIMESTAMPTZ,
  "closingCash" DOUBLE PRECISION,
  "expectedCash" DOUBLE PRECISION DEFAULT 0,
  "difference" DOUBLE PRECISION DEFAULT 0,
  "differenceType" TEXT DEFAULT 'balanced',
  "totalCashSales" DOUBLE PRECISION DEFAULT 0,
  "totalCardSales" DOUBLE PRECISION DEFAULT 0,
  "totalWalletSales" DOUBLE PRECISION DEFAULT 0,
  "totalExpenses" DOUBLE PRECISION DEFAULT 0,
  "totalRefunds" DOUBLE PRECISION DEFAULT 0,
  "transactionCount" INTEGER DEFAULT 0,
  "notes" TEXT DEFAULT '',
  "version" INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS invoices (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "invoiceNumber" TEXT DEFAULT '',
  "orderId" BIGINT,
  "orderSyncId" TEXT,
  "subtotal" DOUBLE PRECISION DEFAULT 0,
  "discount" DOUBLE PRECISION DEFAULT 0,
  "tax" DOUBLE PRECISION DEFAULT 0,
  "total" DOUBLE PRECISION DEFAULT 0,
  "paymentStatus" TEXT DEFAULT 'unpaid' CHECK ("paymentStatus" IN ('unpaid','partial','paid','refunded')),
  "paymentMethod" TEXT DEFAULT 'cash',
  "customerName" TEXT DEFAULT '',
  "customerPhone" TEXT DEFAULT '',
  "customersId" BIGINT,
  "createdBy" TEXT DEFAULT 'unknown',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sync_log (
  "id" BIGSERIAL PRIMARY KEY,
  "direction" TEXT DEFAULT '',
  "startedAt" TIMESTAMPTZ DEFAULT NOW(),
  "inserted" INTEGER DEFAULT 0,
  "updated" INTEGER DEFAULT 0,
  "skipped" INTEGER DEFAULT 0,
  "conflicts" INTEGER DEFAULT 0,
  "errors" INTEGER DEFAULT 0,
  "conflictDetail" TEXT DEFAULT '[]',
  "note" TEXT DEFAULT ''
);

-- =====================================================================
-- جداول المخزون المحسَّن (db.ts + أدوات العميل)
-- =====================================================================

CREATE TABLE IF NOT EXISTS suppliers (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "name" TEXT DEFAULT '',
  "phone" TEXT DEFAULT '',
  "contact" TEXT DEFAULT '',
  "balance" DOUBLE PRECISION DEFAULT 0,
  "paid" DOUBLE PRECISION DEFAULT 0,
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_movements (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "productId" BIGINT,
  "productSyncId" TEXT,
  "quantity" DOUBLE PRECISION DEFAULT 0,
  "type" TEXT DEFAULT '',
  "notes" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_recipes (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "productId" BIGINT,
  "productSyncId" TEXT,
  "ingredient" TEXT DEFAULT '',
  "quantity" DOUBLE PRECISION DEFAULT 0,
  "unit" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS waste_log (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "productId" BIGINT,
  "productSyncId" TEXT,
  "quantity" DOUBLE PRECISION DEFAULT 0,
  "reason" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory_alerts (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "ingredientId" BIGINT,
  "name" TEXT DEFAULT '',
  "quantity" DOUBLE PRECISION DEFAULT 0,
  "minStock" DOUBLE PRECISION DEFAULT 0,
  "cause" TEXT DEFAULT '',
  "status" TEXT DEFAULT 'active',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "resolvedAt" TIMESTAMPTZ
);

-- =====================================================================
-- أقفال الطاولات الاستشارية عبر الأجهزة (Phase 2 advisory locks)
-- =====================================================================

CREATE TABLE IF NOT EXISTS table_locks (
  "table_id" TEXT PRIMARY KEY,
  "locked_by_device" TEXT DEFAULT '',
  "locked_at" TIMESTAMPTZ DEFAULT NOW(),
  "order_id" BIGINT
);

-- =====================================================================
-- الدعوات (invitations) — بدون كلمة مرور، رمز لمرة واحدة
-- =====================================================================

CREATE TABLE IF NOT EXISTS invitations (
  "id" BIGSERIAL PRIMARY KEY,
  "syncId" TEXT,
  "token" TEXT,
  "email" TEXT,
  "employeeId" BIGINT,
  "role" TEXT DEFAULT 'cashier',
  "name" TEXT DEFAULT '',
  "status" TEXT DEFAULT 'pending' CHECK ("status" IN ('pending','used','revoked','expired')),
  "expiresAt" TIMESTAMPTZ,
  "createdBy" BIGINT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================================
-- جداول باتمان (migrations 001/002/003/004)
-- =====================================================================

CREATE TABLE IF NOT EXISTS batman_permissions (
  "id" BIGSERIAL PRIMARY KEY,
  "action" TEXT UNIQUE NOT NULL,
  "description" TEXT DEFAULT '',
  "limitValue" DOUBLE PRECISION DEFAULT 0,
  "requiresApproval" INTEGER DEFAULT 0,
  "autoExecute" INTEGER DEFAULT 1,
  "minRole" TEXT DEFAULT 'cashier',
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS batman_decisions (
  "id" BIGSERIAL PRIMARY KEY,
  "action" TEXT DEFAULT '',
  "requestText" TEXT DEFAULT '',
  "requestJson" TEXT DEFAULT '',
  "decision" TEXT DEFAULT '',
  "reason" TEXT DEFAULT '',
  "actorRole" TEXT DEFAULT '',
  "actorName" TEXT DEFAULT '',
  "amount" DOUBLE PRECISION DEFAULT 0,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "eventId" TEXT DEFAULT ''
);
-- eventId فريد لعالمي (idempotency) — الصفوف القديمة بلا eventId لا تتعارض
CREATE UNIQUE INDEX IF NOT EXISTS ux_batman_decisions_eventId ON batman_decisions("eventId") WHERE "eventId" IS NOT NULL AND "eventId" <> '';

CREATE TABLE IF NOT EXISTS backup_log (
  "id" BIGSERIAL PRIMARY KEY,
  "file" TEXT DEFAULT '',
  "sizeBytes" INTEGER DEFAULT 0,
  "status" TEXT DEFAULT 'ok',
  "note" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================================
-- ذاكرة الـ bot وقاعدة المعرفة (knowledge base / RAG) — للعميل أونلاين
-- =====================================================================

CREATE TABLE IF NOT EXISTS bot_memory (
  "id" BIGSERIAL PRIMARY KEY,
  "type" TEXT DEFAULT 'learned',
  "question" TEXT DEFAULT '',
  "answer" TEXT DEFAULT '',
  "keywords" TEXT DEFAULT '',
  "usageCount" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS knowledge_documents (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "type" TEXT NOT NULL DEFAULT 'text',
  "content" TEXT DEFAULT '',
  "chunksCount" INTEGER DEFAULT 0,
  "tags" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS knowledge_chunks (
  "id" BIGSERIAL PRIMARY KEY,
  "documentId" BIGINT REFERENCES knowledge_documents("id") ON DELETE CASCADE,
  "content" TEXT NOT NULL,
  "chunkIndex" INTEGER NOT NULL DEFAULT 0,
  "tokensEstimate" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================================
-- الفهارس (مطابقة db.ts)
-- =====================================================================

CREATE INDEX IF NOT EXISTS idx_products_category ON products("categoryId");
CREATE INDEX IF NOT EXISTS idx_products_sku ON products("sku");
CREATE INDEX IF NOT EXISTS idx_products_available ON products("available");
CREATE INDEX IF NOT EXISTS idx_order_items_orderId ON order_items("orderId");
CREATE INDEX IF NOT EXISTS idx_order_items_productId ON order_items("productId");
CREATE INDEX IF NOT EXISTS idx_payments_orderId ON payments("orderId");
CREATE INDEX IF NOT EXISTS idx_payments_method ON payments("method");
CREATE INDEX IF NOT EXISTS idx_refunds_orderId ON refunds("orderId");
CREATE INDEX IF NOT EXISTS idx_audit_logs_userId ON audit_logs("userId");
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs("action");
CREATE INDEX IF NOT EXISTS idx_audit_logs_createdAt ON audit_logs("createdAt");
CREATE INDEX IF NOT EXISTS idx_audit_logs_objectType ON audit_logs("objectType");
CREATE INDEX IF NOT EXISTS idx_order_status_history_orderId ON order_status_history("orderId");
CREATE INDEX IF NOT EXISTS idx_orders_orderNumber ON orders("orderNumber");
CREATE INDEX IF NOT EXISTS idx_orders_paymentStatus ON orders("paymentStatus");
CREATE INDEX IF NOT EXISTS idx_orders_orderType ON orders("orderType");
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders("status");
CREATE INDEX IF NOT EXISTS idx_orders_tableId ON orders("tableId");
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders("date");
CREATE INDEX IF NOT EXISTS idx_orders_createdBy ON orders("createdBy");
CREATE INDEX IF NOT EXISTS idx_orders_tableId_status ON orders("tableId", "status");
CREATE INDEX IF NOT EXISTS idx_payments_createdAt ON payments("createdAt");
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses("date");
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses("category");
CREATE INDEX IF NOT EXISTS idx_attendance_employeeId ON attendance("employeeId");
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance("date");
CREATE INDEX IF NOT EXISTS idx_shifts_employeeId ON shifts("employeeId");
CREATE INDEX IF NOT EXISTS idx_shifts_date ON shifts("date");
CREATE INDEX IF NOT EXISTS idx_inventory_name ON inventory("name");
CREATE INDEX IF NOT EXISTS idx_table_locks_locked_at ON table_locks("locked_at");
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations("token");
CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations("email");
CREATE INDEX IF NOT EXISTS idx_batman_decisions_createdAt ON batman_decisions("createdAt");
CREATE INDEX IF NOT EXISTS idx_batman_decisions_action ON batman_decisions("action");
CREATE INDEX IF NOT EXISTS idx_backup_log_createdAt ON backup_log("createdAt");
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_doc ON knowledge_chunks("documentId");
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_type ON knowledge_documents("type");

-- فهارس idempotency لمزامنة الأوردرات وأصنافها (مطابقة ux_orders_syncId في SQLite)
CREATE UNIQUE INDEX IF NOT EXISTS ux_orders_syncId ON orders("syncId") WHERE "syncId" IS NOT NULL AND "syncId" <> '';
CREATE UNIQUE INDEX IF NOT EXISTS ux_order_items_syncId ON order_items("syncId") WHERE "syncId" IS NOT NULL AND "syncId" <> '';

-- فهارس المزامنة الإضافية
CREATE INDEX IF NOT EXISTS idx_orders_syncId ON orders("syncId");
CREATE INDEX IF NOT EXISTS idx_order_items_syncId ON order_items("syncId");
CREATE INDEX IF NOT EXISTS idx_order_items_orderSyncId ON order_items("orderSyncId");
CREATE INDEX IF NOT EXISTS idx_invoices_syncId ON invoices("syncId");
CREATE INDEX IF NOT EXISTS idx_payments_syncId ON payments("syncId");

-- =====================================================================
-- Row Level Security — تفعيل على كل الجداول
-- =====================================================================

ALTER TABLE app_user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tables_store ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE taxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_registers ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE waste_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE table_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE batman_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE batman_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_chunks ENABLE ROW LEVEL SECURITY;

-- القوة الإجبارية: حتى مالك الجدول يخضع ما لم يكن service_role/bypass
ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER TABLE tables_store FORCE ROW LEVEL SECURITY;
ALTER TABLE categories FORCE ROW LEVEL SECURITY;
ALTER TABLE products FORCE ROW LEVEL SECURITY;
ALTER TABLE product_modifiers FORCE ROW LEVEL SECURITY;
ALTER TABLE product_variations FORCE ROW LEVEL SECURITY;
ALTER TABLE payment_methods FORCE ROW LEVEL SECURITY;
ALTER TABLE taxes FORCE ROW LEVEL SECURITY;
ALTER TABLE orders FORCE ROW LEVEL SECURITY;
ALTER TABLE order_items FORCE ROW LEVEL SECURITY;
ALTER TABLE order_status_history FORCE ROW LEVEL SECURITY;
ALTER TABLE payments FORCE ROW LEVEL SECURITY;
ALTER TABLE refunds FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE discounts FORCE ROW LEVEL SECURITY;
ALTER TABLE customers FORCE ROW LEVEL SECURITY;
ALTER TABLE settings FORCE ROW LEVEL SECURITY;
ALTER TABLE inventory FORCE ROW LEVEL SECURITY;
ALTER TABLE purchases FORCE ROW LEVEL SECURITY;
ALTER TABLE employees FORCE ROW LEVEL SECURITY;
ALTER TABLE attendance FORCE ROW LEVEL SECURITY;
ALTER TABLE expenses FORCE ROW LEVEL SECURITY;
ALTER TABLE shifts FORCE ROW LEVEL SECURITY;
ALTER TABLE daily_shifts FORCE ROW LEVEL SECURITY;
ALTER TABLE cash_registers FORCE ROW LEVEL SECURITY;
ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
ALTER TABLE sync_log FORCE ROW LEVEL SECURITY;
ALTER TABLE suppliers FORCE ROW LEVEL SECURITY;
ALTER TABLE stock_movements FORCE ROW LEVEL SECURITY;
ALTER TABLE product_recipes FORCE ROW LEVEL SECURITY;
ALTER TABLE waste_log FORCE ROW LEVEL SECURITY;
ALTER TABLE inventory_alerts FORCE ROW LEVEL SECURITY;
ALTER TABLE table_locks FORCE ROW LEVEL SECURITY;
ALTER TABLE invitations FORCE ROW LEVEL SECURITY;
ALTER TABLE batman_permissions FORCE ROW LEVEL SECURITY;
ALTER TABLE batman_decisions FORCE ROW LEVEL SECURITY;
ALTER TABLE backup_log FORCE ROW LEVEL SECURITY;
ALTER TABLE bot_memory FORCE ROW LEVEL SECURITY;
ALTER TABLE knowledge_documents FORCE ROW LEVEL SECURITY;
ALTER TABLE knowledge_chunks FORCE ROW LEVEL SECURITY;

-- =====================================================================
-- السياسات
-- =====================================================================

-- ---------- عامة / القائمة (مقروءة للجميع حتى anon) ----------
CREATE POLICY "anon_read_categories" ON categories FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_products" ON products FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_product_modifiers" ON product_modifiers FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_product_variations" ON product_variations FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_payment_methods" ON payment_methods FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_taxes" ON taxes FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read_tables" ON tables_store FOR SELECT TO anon USING (true);

-- ---------- app_user_roles: لا يُقرأ ويُكتب إلا من النظام نفسه ----------
-- (المدير يديرها عبر SQL/خدمة، وفق أذونات auth)
CREATE POLICY "roles_admin_all" ON app_user_roles FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- ---------- قوائم SaaS (كتالوج المنيو): أي موظف يقرأ، الكتابة للمدير/الإدارة ----------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['categories','products','product_modifiers','product_variations',
                          'payment_methods','taxes','discounts']
  LOOP
    EXECUTE format('CREATE POLICY "staff_read_%s" ON %I FOR SELECT TO authenticated USING (is_staff());', t, t);
    EXECUTE format('CREATE POLICY "manager_insert_%s" ON %I FOR INSERT TO authenticated WITH CHECK (is_manager());', t, t);
    EXECUTE format('CREATE POLICY "manager_update_%s" ON %I FOR UPDATE TO authenticated USING (is_manager()) WITH CHECK (is_manager());', t, t);
    EXECUTE format('CREATE POLICY "manager_delete_%s" ON %I FOR DELETE TO authenticated USING (is_manager());', t, t);
  END LOOP;
END $$;

-- ---------- بيانات تشغيل الكاشير: قراءة+كتابة للكاشير فأعلى (مطابق ROLE_PERMISSIONS) ----------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['orders','order_items','order_status_history','payments','refunds',
                          'customers','invoices','cash_registers','tables_store','table_locks']
  LOOP
    EXECUTE format('CREATE POLICY "staff_all_%s" ON %I FOR ALL TO authenticated USING (is_staff()) WITH CHECK (is_staff());', t, t);
  END LOOP;
END $$;

-- ---------- البيانات التشغيلية للكتابة المقيّدة: قراءة للكاشير، كتابة للمدير/الإدارة ----------
-- (مطابق ROLE_PERMISSIONS: categories/products.write, inventory.write, expenses.write,
--   purchases.write, attendance.write, shifts.write, daily-shifts.write → manager فقط)
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['inventory','purchases','expenses','attendance','shifts','daily_shifts',
                          'suppliers','stock_movements','product_recipes','waste_log','inventory_alerts']
  LOOP
    EXECUTE format('CREATE POLICY "staff_read_%s" ON %I FOR SELECT TO authenticated USING (is_staff());', t, t);
    EXECUTE format('CREATE POLICY "manager_insert_%s" ON %I FOR INSERT TO authenticated WITH CHECK (is_manager());', t, t);
    EXECUTE format('CREATE POLICY "manager_update_%s" ON %I FOR UPDATE TO authenticated USING (is_manager()) WITH CHECK (is_manager());', t, t);
    EXECUTE format('CREATE POLICY "manager_delete_%s" ON %I FOR DELETE TO authenticated USING (is_manager());', t, t);
  END LOOP;
END $$;

-- ---------- الإعدادات: قراءة للجميع، كتابة للمدير/المدير ----------
CREATE POLICY "staff_read_settings" ON settings FOR SELECT TO authenticated USING (is_staff());
CREATE POLICY "manager_insert_settings" ON settings FOR INSERT TO authenticated WITH CHECK (is_manager());
CREATE POLICY "manager_update_settings" ON settings FOR UPDATE TO authenticated USING (is_manager()) WITH CHECK (is_manager());
CREATE POLICY "manager_delete_settings" ON settings FOR DELETE TO authenticated USING (is_manager());

-- ---------- الموظفون: قراءة للجميع، كتابة للمدير/الإدارة (delete_employee = manager فقط) ----------
CREATE POLICY "staff_read_employees" ON employees FOR SELECT TO authenticated USING (is_staff());
CREATE POLICY "manager_insert_employees" ON employees FOR INSERT TO authenticated WITH CHECK (is_manager());
CREATE POLICY "manager_update_employees" ON employees FOR UPDATE TO authenticated USING (is_manager()) WITH CHECK (is_manager());
CREATE POLICY "manager_delete_employees" ON employees FOR DELETE TO authenticated USING (is_manager());

-- ---------- المستخدمون (يحوي تجزئات كلمات المرور): الإدارة فقط ----------
CREATE POLICY "admin_read_users" ON users FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin_insert_users" ON users FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "admin_update_users" ON users FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "admin_delete_users" ON users FOR DELETE TO authenticated USING (is_admin());

-- ---------- التدقيق: كتابة للجميع (السجل يُكتب تلقائياً)، قراءة للإدارة ----------
CREATE POLICY "staff_insert_audit_logs" ON audit_logs FOR INSERT TO authenticated WITH CHECK (is_staff());
CREATE POLICY "manager_read_audit_logs" ON audit_logs FOR SELECT TO authenticated USING (is_manager());
CREATE POLICY "admin_delete_audit_logs" ON audit_logs FOR DELETE TO authenticated USING (is_admin());

-- ---------- سجل المزامنة: إدراج للجميع، قراءة للجميع (تشخيص) ----------
CREATE POLICY "staff_all_sync_log" ON sync_log FOR ALL TO authenticated USING (is_staff()) WITH CHECK (is_staff());

-- ---------- باتمان: الأذونات قراءة للجميع/كتابة مدير؛ القرارات سجل إدراج+قراءة، حذف إدارة ----------
CREATE POLICY "staff_read_batman_permissions" ON batman_permissions FOR SELECT TO authenticated USING (is_staff());
CREATE POLICY "manager_insert_batman_permissions" ON batman_permissions FOR INSERT TO authenticated WITH CHECK (is_manager());
CREATE POLICY "manager_update_batman_permissions" ON batman_permissions FOR UPDATE TO authenticated USING (is_manager()) WITH CHECK (is_manager());
CREATE POLICY "manager_delete_batman_permissions" ON batman_permissions FOR DELETE TO authenticated USING (is_manager());

CREATE POLICY "staff_insert_batman_decisions" ON batman_decisions FOR INSERT TO authenticated WITH CHECK (is_staff());
CREATE POLICY "staff_read_batman_decisions" ON batman_decisions FOR SELECT TO authenticated USING (is_staff());
CREATE POLICY "admin_delete_batman_decisions" ON batman_decisions FOR DELETE TO authenticated USING (is_admin());

-- ---------- النسخ الاحتياطي: عرض للجميع، إدراج الإدارة ----------
CREATE POLICY "staff_read_backup_log" ON backup_log FOR SELECT TO authenticated USING (is_staff());
CREATE POLICY "admin_write_backup_log" ON backup_log FOR INSERT TO authenticated WITH CHECK (is_admin());

-- ---------- الدعوات: قراءة للجميع، كتابة مدير ----------
CREATE POLICY "staff_read_invitations" ON invitations FOR SELECT TO authenticated USING (is_staff());
CREATE POLICY "manager_insert_invitations" ON invitations FOR INSERT TO authenticated WITH CHECK (is_manager());
CREATE POLICY "manager_update_invitations" ON invitations FOR UPDATE TO authenticated USING (is_manager()) WITH CHECK (is_manager());
CREATE POLICY "manager_delete_invitations" ON invitations FOR DELETE TO authenticated USING (is_manager());

-- ---------- ذاكرة البوت / قاعدة المعرفة: أي موظف ----------
CREATE POLICY "staff_all_bot_memory" ON bot_memory FOR ALL TO authenticated USING (is_staff()) WITH CHECK (is_staff());
CREATE POLICY "staff_all_knowledge_documents" ON knowledge_documents FOR ALL TO authenticated USING (is_staff()) WITH CHECK (is_staff());
CREATE POLICY "staff_all_knowledge_chunks" ON knowledge_chunks FOR ALL TO authenticated USING (is_staff()) WITH CHECK (is_staff());

-- =====================================================================
-- منح الصلاحيات لـ PostgREST (anon/authenticated)
-- Row Level Security تبقى الحماية الفعلية — المنح تجعل التقييم ممكن الشكل فقط
-- =====================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.current_app_role TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.role_in TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_staff TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_manager TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- =====================================================================
-- البيانات الافتراضية (مطابقة db.ts seeds)
-- =====================================================================

-- المدير الافتراضي — كلمة '123456' مؤقتة MUST CHANGE (نفس سلوك SQLite) —
-- عند أول دخول يُجبَر على تغييرها، ولن تعمل بعدها أبداً.
INSERT INTO users ("username", "password", "name", "role", "mustChangePassword", "active")
SELECT 'admin', '123456', 'مدير النظام', 'admin', 1, 1
WHERE NOT EXISTS (SELECT 1 FROM users WHERE "username"='admin');

-- الطاولات (1-14) — نفس تقسيم SQLite
INSERT INTO tables_store ("id", "number", "status", "capacity", "zone")
SELECT v.id, v.id, 'available', v.cap, v.zone
FROM (VALUES
  (1,4,'صالة'),(2,4,'صالة'),(3,4,'صالة'),(4,4,'صالة'),(5,4,'صالة'),(6,4,'صالة'),(7,4,'صالة'),
  (8,6,'VIP'),(9,6,'VIP'),(10,6,'VIP'),(11,6,'VIP'),
  (12,6,'خارجي'),(13,6,'خارجي'),(14,6,'خارجي')
) AS v(id, cap, zone)
WHERE NOT EXISTS (SELECT 1 FROM tables_store);

-- إعادة مزامنة تسلسل الطاولات بعد الإدراج الصريح بأرقام 1-14
SELECT setval(pg_get_serial_sequence('tables_store', 'id'), COALESCE((SELECT MAX("id") FROM tables_store), 1), true);

-- طرق الدفع (8 افتراضية)
INSERT INTO payment_methods ("name", "name_en", "type", "icon", "sortOrder", "active")
SELECT * FROM (VALUES
  ('كاش','Cash','cash','💵',1,1),
  ('فيزا','Visa','card','💳',2,1),
  ('ماستركارد','Mastercard','card','💳',3,1),
  ('انستاباي','InstaPay','wallet','📱',4,1),
  ('فودافون كاش','Vodafone Cash','wallet','📱',5,1),
  ('تحويل بنكي','Bank Transfer','bank','🏦',6,1),
  ('محفظة','Wallet','wallet','👛',7,1),
  ('أخرى','Other','other','💰',8,1)
) AS v(name, name_en, type, icon, sortOrder, active)
WHERE NOT EXISTS (SELECT 1 FROM payment_methods);

-- الضريبة الافتراضية
INSERT INTO taxes ("name", "rate", "active", "appliesTo")
SELECT 'ضريبة القيمة المضافة', 14, 1, 'all'
WHERE NOT EXISTS (SELECT 1 FROM taxes);

-- الأقسام الافتراضية
INSERT INTO categories ("name", "name_en", "icon", "sortOrder")
SELECT * FROM (VALUES
  ('القهوة المختصه','specialty','☕',1),('قسم القهوة','coffee','☕',2),
  ('مشروبات ساخنة','hot','🫖',3),('القهوة المثلجة','iced','🧊',4),
  ('ميلك شيك','milkshake','🥤',5),('عصائر فريش','juice','🍹',6),
  ('سموزي','smoothie','🥭',7),('مشروبات صودا','soda','🍋',8),
  ('مشروبات غازية وطاقة','cans','🥫',9),('الحلويات','desserts','🍰',10),
  ('الفطور','breakfast','🥪',11),('البيتزا','pizza','🍕',12),
  ('الإضافات','addons','➕',13),('مشروبات شتوية','winter','🍂',14)
) AS v(name, name_en, icon, sortOrder)
WHERE NOT EXISTS (SELECT 1 FROM categories);

-- المنتجات (كاملة من قائمة db.ts)
INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('V60',80,1),('آيس دريب',80,2),('قهوة اليوم',50,3),('Aeropress',75,4),('French Press',70,5)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='specialty'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('إسبريسو',45,1),('إسبريسو دبل',70,2),('قهوة تركي',35,3),('قهوة فرنساوي',65,4),('قهوة بندق',70,5),
  ('ميكاتو',50,6),('ميكاتو دبل',80,7),('موكا',75,8),('وايت موكا',75,9),('لاتيه',85,10),
  ('كابتشينو',85,11),('كورتادو',75,12),('نسكافيه',70,13),('هوت شوكليت',70,14),('هوت شوكليت نوتيلا',80,15),
  ('فلات وايت',80,16),('اسبانش لاتيه',90,17)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='coffee'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('شاي',35,1),('شاي كرك',50,2),('شاي أخضر',35,3),('ميكس أعشاب',50,4),('شاي بالبن',50,5),
  ('أعشاب',35,6),('هوت سيدر',50,7)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='hot'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('آيس كوفي',80,1),('آيس لاتيه',85,2),('آيس موكا',90,3),('آيس وايت موكا',90,4),('فرابتشينو',95,5),
  ('فرابيه كلاسيك',85,6),('فرابيه فروت',95,7),('آيس اسبانش لاتيه',95,8)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='iced'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('ميلك شيك شوكولاتة',90,1),('ميلك شيك فانيليا',90,2),('ميلك شيك فراولة',90,3),('ميلك شيك مانجو',90,4),
  ('ميلك شيك نوتيلا',100,5),('ميلك شيك أوريو',110,6),('ميلك شيك كراميل',90,7),('ميلك شيك ميكس شوكليت',120,8)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='milkshake'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('مانجو',90,1),('فراولة',80,2),('جوافة',75,3),('برتقال',75,4),('ليمون',70,5),('ليمون بالنعناع',75,6),('كيوي',90,7)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='juice'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('سموزي مانجو',75,1),('سموزي فراولة',75,2),('سموزي كوكتيل',75,3),('سموزي كيوي',85,4),('سموزي موز',75,5)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='smoothie'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('موهيتو',75,1),('موهيتو فليفر',100,2),('بينا كولادا',75,3),('ميكس لوكا',80,4),('جيلي كولا',75,5),
  ('صن شاين',75,6),('صن رايز',75,7),('شيري كولا',75,8),('ميكس بيري',80,9),('بلو بيري فراولة',75,10),
  ('باشون أناناس',75,11),('ريدبول فليفر',120,12)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='soda'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('بيبسي',35,1),('سفن أب',35,2),('ميرندا',35,3),('ريد بول',85,4),('تويست',35,5),('فيروز',40,6),('بيريل',50,7),('مياه',10,8)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='cans'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('وافل كلاسيك',80,1),('وافل شوكليت',140,2),('سان سيباستيان',70,3),('مولتن',80,4),('براونيز',80,5),
  ('كوكيز',40,6),('أم علي',90,7),('وافل فورسيزون',120,8),('وافل بابل',85,9),('وافل فواكه',110,10),
  ('تشيز كيك',90,11),('موس جالاكسي',100,12),('ريد فالفيت',95,13)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='desserts'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('توست ميكس جبن (نصف)',30,1),('توست ميكس جبن (كامل)',60,2),('توست بسطرمة (نصف)',35,3),('توست بسطرمة (كامل)',70,4),
  ('توست روزبيف (نصف)',35,5),('توست روزبيف (كامل)',70,6),('توست رومي مدخن (نصف)',35,7),('توست رومي مدخن (كامل)',70,8),
  ('توست كفيار (نصف)',50,9),('توست كفيار (كامل)',100,10),('ساندويتش ميكس جبن',25,11),('ساندويتش بسطرمة',30,12),
  ('كرواسون',65,13),('شباتا',65,14),('باجيت',65,15)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='breakfast'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('بيتزا سي فود',250,1),('بيتزا سلامي',170,2),('بيتزا رانش',200,3),('بيتزا دجاج',200,4),('بيتزا مارجريتا',150,5),
  ('بيتزا تشيكن باربكيو',180,6),('بيتزا اسبايسي رانش',190,7),('بيتزا سوبر سوبريم',220,8)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='pizza'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('جبن',15,1),('شيكولاتة',15,2),('مكسرات',20,3),('نوتيلا',25,4),('كارت',5,5),('طاولة',20,6)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='addons'
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO products ("name", "categoryId", "price", "sortOrder")
SELECT i.name, c."id", i.price, i.sort
FROM (VALUES
  ('سحلب',85,1),('سحلب نوتيلا',90,2),('حمص الشام',80,3),('بليلة',85,4),('شاي كرك',50,5),
  ('قرفة',50,6),('ينسون',40,7),('زنجبيل',40,8),('بابونج',40,9)
) AS i(name, price, sort)
JOIN categories c ON c."name_en"='winter'
WHERE NOT EXISTS (SELECT 1 FROM products);

-- صلاحيات باتمان الافتراضية (مطابقة migration 001)
INSERT INTO batman_permissions ("action", "description", "limitValue", "requiresApproval", "autoExecute", "minRole") VALUES
  ('add_expense', 'تسجيل مصروف — حتى 500 ل.س تلقائي للكاشير، وما فوقه يتطلب تأكيداً صريحاً', 500, 1, 1, 'cashier'),
  ('add_purchase', 'تسجيل مشتريات/فاتورة مورد — 1000 ل.س أو أكثر يتطلب موافقة مدير', 1000, 1, 1, 'cashier'),
  ('record_invoice', 'تسجيل فاتورة يدوية (بيع خارجي) — حتى 1000 ل.س تلقائي', 1000, 1, 1, 'cashier'),
  ('update_price', 'تعديل سعر صنف — محدود للمدير/الإدارة دائماً', 0, 1, 0, 'manager'),
  ('delete_employee', 'حذف موظف — محدود للمدير/الإدارة دائماً', 0, 1, 0, 'manager'),
  ('view_net_profit', 'تصفير/عرض تقارير الأرباح الصافية — الإدارة فقط', 0, 1, 0, 'admin'),
  ('view_reports', 'عرض التقارير — مدير/إدارة', 0, 0, 1, 'manager')
ON CONFLICT ("action") DO NOTHING;

-- =====================================================================
-- ملاحظات ما بعد التشغيل:
--  1) لصق هذا الملف كاملاً في SQL Editor ثم تشغيله مرتين للتأكد (idempotent).
--  2) بعدها شغّل deploy/supabase-rls-seed.sql لإنشاء مستخدمي Auth تجريبيين.
--  3) نفّذ tools/test-supabase-rls.cjs للتحقق التجريبي من عزل الأدوار.
--  4) تعديل جدول app_user_roles لربط كل موظف حقيقي بدوره:
--     INSERT INTO app_user_roles (user_id, role) VALUES (uuid_from_auth, 'cashier');
-- =====================================================================